(define (fast-mult a b)
  (define (double x)
	(* x 2))
  (define (halve x)
	(/ x 2))
  (define (even? n)
	(= (remainder n 2) 0))
  (cond ((= b 0) 0)
		((even? b) (double (fast-mult a (halve b))))
		(else (+ a (fast-mult a (- b 1))))))
