(define (mult i j)
  (define (double x)
	(* x 2))
  (define (halve x)
	(/ x 2))
  (define (even? n)
	(= (remainder n 2) 0))
  (define (iter-mult a i j)
  	(cond ((= j 0) a)
		  ((even? j) (iter-mult a (double i) (halve j)))
		  (else (iter-mult (+ a i) i (- j 1)))))
  (iter-mult 0 i j))
